stages:
  - Deploy

Deploy:PDF:
  image: registry.gitlab.com/severinkaderli/pandoc-docker:latest
  stage: Deploy
  script:
    - export GIT_SSL_NO_VERIFY=1
    - git clone https://gitlab.com/severinkaderli/pandoc-latex-templates .latex
    - .latex/build.sh ./doc/diary.md
#   - .latex/build.sh ./doc/task_01/task_01.md
#   - .latex/build.sh ./doc/task_01/task_01_presentation.md beamer
#   - .latex/build.sh ./doc/task_02/task_02.md
#   - .latex/build.sh ./doc/task_02/task_02_presentation.md beamer
#    - .latex/build.sh ./doc/task_03/task_03.md
    - .latex/build.sh ./doc/task_04/task_04.md
    - .latex/build.sh ./doc/task_04/task_04_presentation.md beamer
  artifacts:
    paths:
      - "*.pdf"

Deploy:App:
  image: maven:3-jdk-8-alpine
  stage: Deploy
  script:
    - cd calc
    - mvn clean install
    - mv target/*.war ..
  artifacts:
    paths:
      - "*.war"
