-- noinspection SqlNoDataSourceInspectionForFile
-- to import this into SQLITE, use :%s/AUTO_INCREMENT/AUTOINCREMENT/g

DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS THERAPIST;

CREATE TABLE PERSON
(
    "ID"         INTEGER      NOT NULL,
    "AHV"        INTEGER      NOT NULL,
    "FIRST_NAME" VARCHAR(255) NOT NULL,
    "LAST_NAME"  VARCHAR(255) NOT NULL,
    "USER_NAME"  VARCHAR(255) NOT NULL,
    "BIRTH_DATE" TIMESTAMP    NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE CONTACT
(
    "ID"        INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    "PHONE"     VARCHAR(255),
    "EMAIL"     VARCHAR(255),
    "STREET"    VARCHAR(255),
    "CITY"      VARCHAR(255),
    "COUNTRY"   VARCHAR(255),
    "PERSON_ID" INTEGER NOT NULL UNIQUE
);

CREATE TABLE PATIENT
(
    "ID"           INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    "PATIENT_ID"   INTEGER NOT NULL,
    "THERAPIST_ID" INTEGER
);

CREATE TABLE THERAPIST
(
    "ID" INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT
);